version: "3.8"
services:
  app:
    build: .
    depends_on:
      - db
    command: python app/main/app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/quickml
    restart: on-failure:10
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: quickml2
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

